In [1]:
# Esteban Quintero Sotomayor - 20110388.

import pandas as pd
import matplotlib.pylab as plt
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Read Multiple sheets
dictDf = pd.read_excel('Canada.xlsx', sheet_name = ['Regions by Citizenship', 'Canada by Citizenship', 'Canada by Citizenship2'])

# Get DataFrame from Dict
regionsByCitizenshipDf = dictDf.get('Regions by Citizenship')
canadaByCitizenshipDf = dictDf.get('Canada by Citizenship')
canadaByCitizenship2Df = dictDf.get('Canada by Citizenship2')

In [2]:
# Print first DataFrame = first sheet
regionsByCitizenshipDf

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United Nations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Population Division,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Department of Economic and Social Affairs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,International Migration Flows to and from Sele...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,POP/DB/MIG/Flow/Rev.2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,December 2015 - Copyright Â© 2015 by United Nat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Suggested citation: United Nations, Department...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,International Migration Flows to and from Sel...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Reporting country: Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Criterion: Citizenship,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Classification,NaN,Regional aggregates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012.0,2013.0
20,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1.0,NaN
21,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846.0,NaN
22,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602.0,NaN
23,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453.0,NaN
24,Immigrants,Foreigners,Africa,Southern Africa,1041,1126,791,387,297,327,...,1203,1012,1148,1230,1184,1235,1306,1049,1348.0,NaN
25,Immigrants,Foreigners,Africa,Western Africa,306,301,210,222,271,319,...,4333,5303,5751,5684,5511,6802,8355,6578,7834.0,NaN
26,Immigrants,Foreigners,Africa Total,NaN,3951,4363,3819,2671,2639,2650,...,28192,27523,29188,28284,29890,34534,40892,35441,38083.0,NaN
27,Immigrants,Foreigners,Asia,Central Asia,..,..,..,..,..,..,...,995,1134,903,936,805,962,905,769,1029.0,NaN
28,Immigrants,Foreigners,Asia,Eastern Asia,6836,8895,5481,3254,2624,2979,...,43550,50306,41763,35591,39602,37497,37954,35159,40449.0,NaN
29,Immigrants,Foreigners,Asia,South-Eastern Asia,8693,9191,9022,8845,12161,9787,...,18056,22809,25105,27256,30614,34166,44199,40494,37695.0,NaN
30,Immigrants,Foreigners,Asia,Southern Asia,11315,11566,11591,10157,9607,7654,...,58521,69510,66742,56032,54154,53083,62284,53673,60568.0,NaN
31,Immigrants,Foreigners,Asia,Western Asia,4181,4662,4120,2440,2882,3430,...,13728,15494,14541,13644,14719,15726,18503,16799,12477.0,NaN
32,Immigrants,Foreigners,Asia Total,NaN,31025,34314,30214,24696,27274,23850,...,134850,159253,149054,133459,139894,141434,163845,146894,152218.0,NaN
33,Immigrants,Foreigners,Europe,Eastern Europe,1467,3698,6873,5459,4433,3969,...,18360,16724,14389,13886,11988,11759,11803,9612,9464.0,NaN
34,Immigrants,Foreigners,Europe,Northern Europe,23721,26608,22134,10725,10845,10212,...,8486,8153,7969,9186,10042,9846,9816,7285,7616.0,NaN
35,Immigrants,Foreigners,Europe,Southern Europe,7762,7037,5222,3083,3033,2868,...,3200,2806,2417,2290,2692,2948,2661,2466,2854.0,NaN
36,Immigrants,Foreigners,Europe,Western Europe,6810,7459,8491,5371,3976,3795,...,8036,8272,8278,8133,9970,10525,9145,7415,9243.0,NaN
37,Immigrants,Foreigners,Europe Total,NaN,39760,44802,42720,24638,22287,20844,...,38082,35955,33053,33495,34692,35078,33425,26778,29177.0,NaN
38,Immigrants,Foreigners,Latin America and the Caribbean,Caribbean,7045,8310,8326,6998,5553,6048,...,6630,6816,6652,7826,8862,8847,10549,11958,11898.0,NaN
39,Immigrants,Foreigners,Latin America and the Caribbean,Central America,734,921,1612,3648,4087,4862,...,3346,3990,4140,5039,4891,4814,5692,5821,6019.0,NaN
40,Immigrants,Foreigners,Latin America and the Caribbean,South America,5302,5984,6831,4781,4038,4261,...,12205,13941,13884,13146,12794,13206,12577,10077,9256.0,NaN
41,Immigrants,Foreigners,Latin America and the Caribbean Total,NaN,13081,15215,16769,15427,13678,15171,...,22181,24747,24676,26011,26547,26867,28818,27856,27173.0,NaN
42,Immigrants,Foreigners,Northern America,Northern America,9378,10030,9074,7100,6661,6543,...,6990,8394,9613,9463,10190,8995,8142,7676,7891.0,NaN
43,Immigrants,Foreigners,Oceania,Australia and New Zealand,1304,1119,848,457,481,467,...,1280,1279,1193,1383,1498,1538,1423,1226,1399.0,NaN
44,Immigrants,Foreigners,Oceania,Melanesia,632,707,816,558,391,448,...,497,300,278,304,331,313,401,316,273.0,NaN
45,Immigrants,Foreigners,Oceania,Micronesia,1,..,..,1,..,..,...,1,2,1,3,1,2,..,..,2.0,NaN
46,Immigrants,Foreigners,Oceania,Polynesia,5,13,11,2,6,5,...,10,4,1,3,4,7,10,6,5.0,NaN
47,Immigrants,Foreigners,Oceania Total,NaN,1942,1839,1675,1018,878,920,...,1788,1585,1473,1693,1834,1860,1834,1548,1679.0,NaN
48,Immigrants,Foreigners,Unknown,Unknown,44000,18078,16904,13635,14855,14368,...,3739,4785,4583,4348,4197,3402,3731,2554,1681.0,NaN

In [3]:
# Drop specific rows range, in this case from 0 to 18. Not hardcode axis needed, implicit axis = 0 = rows
regionsByCitizenshipDf = regionsByCitizenshipDf.drop(range(0, 19))

In [4]:
regionsByCitizenshipDf

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
19,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012.0,2013.0
20,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1.0,NaN
21,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846.0,NaN
22,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602.0,NaN
23,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453.0,NaN
24,Immigrants,Foreigners,Africa,Southern Africa,1041,1126,791,387,297,327,...,1203,1012,1148,1230,1184,1235,1306,1049,1348.0,NaN
25,Immigrants,Foreigners,Africa,Western Africa,306,301,210,222,271,319,...,4333,5303,5751,5684,5511,6802,8355,6578,7834.0,NaN
26,Immigrants,Foreigners,Africa Total,NaN,3951,4363,3819,2671,2639,2650,...,28192,27523,29188,28284,29890,34534,40892,35441,38083.0,NaN
27,Immigrants,Foreigners,Asia,Central Asia,..,..,..,..,..,..,...,995,1134,903,936,805,962,905,769,1029.0,NaN
28,Immigrants,Foreigners,Asia,Eastern Asia,6836,8895,5481,3254,2624,2979,...,43550,50306,41763,35591,39602,37497,37954,35159,40449.0,NaN
29,Immigrants,Foreigners,Asia,South-Eastern Asia,8693,9191,9022,8845,12161,9787,...,18056,22809,25105,27256,30614,34166,44199,40494,37695.0,NaN
30,Immigrants,Foreigners,Asia,Southern Asia,11315,11566,11591,10157,9607,7654,...,58521,69510,66742,56032,54154,53083,62284,53673,60568.0,NaN
31,Immigrants,Foreigners,Asia,Western Asia,4181,4662,4120,2440,2882,3430,...,13728,15494,14541,13644,14719,15726,18503,16799,12477.0,NaN
32,Immigrants,Foreigners,Asia Total,NaN,31025,34314,30214,24696,27274,23850,...,134850,159253,149054,133459,139894,141434,163845,146894,152218.0,NaN
33,Immigrants,Foreigners,Europe,Eastern Europe,1467,3698,6873,5459,4433,3969,...,18360,16724,14389,13886,11988,11759,11803,9612,9464.0,NaN
34,Immigrants,Foreigners,Europe,Northern Europe,23721,26608,22134,10725,10845,10212,...,8486,8153,7969,9186,10042,9846,9816,7285,7616.0,NaN
35,Immigrants,Foreigners,Europe,Southern Europe,7762,7037,5222,3083,3033,2868,...,3200,2806,2417,2290,2692,2948,2661,2466,2854.0,NaN
36,Immigrants,Foreigners,Europe,Western Europe,6810,7459,8491,5371,3976,3795,...,8036,8272,8278,8133,9970,10525,9145,7415,9243.0,NaN
37,Immigrants,Foreigners,Europe Total,NaN,39760,44802,42720,24638,22287,20844,...,38082,35955,33053,33495,34692,35078,33425,26778,29177.0,NaN
38,Immigrants,Foreigners,Latin America and the Caribbean,Caribbean,7045,8310,8326,6998,5553,6048,...,6630,6816,6652,7826,8862,8847,10549,11958,11898.0,NaN
39,Immigrants,Foreigners,Latin America and the Caribbean,Central America,734,921,1612,3648,4087,4862,...,3346,3990,4140,5039,4891,4814,5692,5821,6019.0,NaN
40,Immigrants,Foreigners,Latin America and the Caribbean,South America,5302,5984,6831,4781,4038,4261,...,12205,13941,13884,13146,12794,13206,12577,10077,9256.0,NaN
41,Immigrants,Foreigners,Latin America and the Caribbean Total,NaN,13081,15215,16769,15427,13678,15171,...,22181,24747,24676,26011,26547,26867,28818,27856,27173.0,NaN
42,Immigrants,Foreigners,Northern America,Northern America,9378,10030,9074,7100,6661,6543,...,6990,8394,9613,9463,10190,8995,8142,7676,7891.0,NaN
43,Immigrants,Foreigners,Oceania,Australia and New Zealand,1304,1119,848,457,481,467,...,1280,1279,1193,1383,1498,1538,1423,1226,1399.0,NaN
44,Immigrants,Foreigners,Oceania,Melanesia,632,707,816,558,391,448,...,497,300,278,304,331,313,401,316,273.0,NaN
45,Immigrants,Foreigners,Oceania,Micronesia,1,..,..,1,..,..,...,1,2,1,3,1,2,..,..,2.0,NaN
46,Immigrants,Foreigners,Oceania,Polynesia,5,13,11,2,6,5,...,10,4,1,3,4,7,10,6,5.0,NaN
47,Immigrants,Foreigners,Oceania Total,NaN,1942,1839,1675,1018,878,920,...,1788,1585,1473,1693,1834,1860,1834,1548,1679.0,NaN
48,Immigrants,Foreigners,Unknown,Unknown,44000,18078,16904,13635,14855,14368,...,3739,4785,4583,4348,4197,3402,3731,2554,1681.0,NaN

In [5]:
# For easiest reading
regionsByCitizenshipDf.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
19,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012.0,2013.0
20,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1.0,NaN
21,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846.0,NaN
22,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602.0,NaN
23,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453.0,NaN

In [6]:
# Rename columns
headers = ["Unnamed: 0", "Unnamed: 1", "Unnamed: 2", "Unnamed: 3", "Unnamed: 4", "Unnamed: 5", "Unnamed: 6", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9", 
           "Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "Unnamed: 14", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17", "Unnamed: 18", "Unnamed: 19", 
           "Unnamed: 20", "Unnamed: 21", "Unnamed: 22", "Unnamed: 23", "Unnamed: 24", "Unnamed: 25", "Unnamed: 26", "Unnamed: 27", "Unnamed: 28", "Unnamed: 29", 
           "Unnamed: 30", "Unnamed: 31", "Unnamed: 32", "Unnamed: 33", "Unnamed: 34", "Unnamed: 35", "Unnamed: 36", "Unnamed: 37"]

regionsByCitizenshipDf.columns = headers
regionsByCitizenshipDf = regionsByCitizenshipDf.rename(columns = {'Unnamed: 0':'Type', 'Unnamed: 1':'Coverage', 'Unnamed: 2':'AreaName', 'Unnamed: 3':'RegName', 'Unnamed: 4':'1980', 'Unnamed: 5':'1981', 'Unnamed: 6':'1982', 'Unnamed: 7':'1983', 'Unnamed: 8':'1984', 'Unnamed: 9':'1985',
                                                                  'Unnamed: 10':'1986', 'Unnamed: 11':'1987', 'Unnamed: 12':'1988', 'Unnamed: 13':'1989', 'Unnamed: 14':'1990', 'Unnamed: 15':'1991', 'Unnamed: 16':'1992', 'Unnamed: 17':'1993', 'Unnamed: 18':'1994', 'Unnamed: 19':'1995',
                                                                  'Unnamed: 20':'1996', 'Unnamed: 21':'1997', 'Unnamed: 22':'1998', 'Unnamed: 23':'1999', 'Unnamed: 24':'2000', 'Unnamed: 25':'2001', 'Unnamed: 26':'2002', 'Unnamed: 27':'2003', 'Unnamed: 28':'2004', 'Unnamed: 29':'2005',
                                                                  'Unnamed: 30':'2006', 'Unnamed: 31':'2007', 'Unnamed: 32':'2008', 'Unnamed: 33':'2009', 'Unnamed: 34':'2010', 'Unnamed: 35':'2011', 'Unnamed: 36':'2012', 'Unnamed: 37':'2013'}, inplace = False)

In [7]:
regionsByCitizenshipDf.head()

,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
19,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012.0,2013.0
20,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1.0,NaN
21,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846.0,NaN
22,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602.0,NaN
23,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453.0,NaN

In [8]:
# Delete specific row
regionsByCitizenshipDf.drop(19, axis=0, inplace=True)

In [9]:
regionsByCitizenshipDf

,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
20,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1.0,NaN
21,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846.0,NaN
22,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602.0,NaN
23,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453.0,NaN
24,Immigrants,Foreigners,Africa,Southern Africa,1041,1126,791,387,297,327,...,1203,1012,1148,1230,1184,1235,1306,1049,1348.0,NaN
25,Immigrants,Foreigners,Africa,Western Africa,306,301,210,222,271,319,...,4333,5303,5751,5684,5511,6802,8355,6578,7834.0,NaN
26,Immigrants,Foreigners,Africa Total,NaN,3951,4363,3819,2671,2639,2650,...,28192,27523,29188,28284,29890,34534,40892,35441,38083.0,NaN
27,Immigrants,Foreigners,Asia,Central Asia,..,..,..,..,..,..,...,995,1134,903,936,805,962,905,769,1029.0,NaN
28,Immigrants,Foreigners,Asia,Eastern Asia,6836,8895,5481,3254,2624,2979,...,43550,50306,41763,35591,39602,37497,37954,35159,40449.0,NaN
29,Immigrants,Foreigners,Asia,South-Eastern Asia,8693,9191,9022,8845,12161,9787,...,18056,22809,25105,27256,30614,34166,44199,40494,37695.0,NaN
30,Immigrants,Foreigners,Asia,Southern Asia,11315,11566,11591,10157,9607,7654,...,58521,69510,66742,56032,54154,53083,62284,53673,60568.0,NaN
31,Immigrants,Foreigners,Asia,Western Asia,4181,4662,4120,2440,2882,3430,...,13728,15494,14541,13644,14719,15726,18503,16799,12477.0,NaN
32,Immigrants,Foreigners,Asia Total,NaN,31025,34314,30214,24696,27274,23850,...,134850,159253,149054,133459,139894,141434,163845,146894,152218.0,NaN
33,Immigrants,Foreigners,Europe,Eastern Europe,1467,3698,6873,5459,4433,3969,...,18360,16724,14389,13886,11988,11759,11803,9612,9464.0,NaN
34,Immigrants,Foreigners,Europe,Northern Europe,23721,26608,22134,10725,10845,10212,...,8486,8153,7969,9186,10042,9846,9816,7285,7616.0,NaN
35,Immigrants,Foreigners,Europe,Southern Europe,7762,7037,5222,3083,3033,2868,...,3200,2806,2417,2290,2692,2948,2661,2466,2854.0,NaN
36,Immigrants,Foreigners,Europe,Western Europe,6810,7459,8491,5371,3976,3795,...,8036,8272,8278,8133,9970,10525,9145,7415,9243.0,NaN
37,Immigrants,Foreigners,Europe Total,NaN,39760,44802,42720,24638,22287,20844,...,38082,35955,33053,33495,34692,35078,33425,26778,29177.0,NaN
38,Immigrants,Foreigners,Latin America and the Caribbean,Caribbean,7045,8310,8326,6998,5553,6048,...,6630,6816,6652,7826,8862,8847,10549,11958,11898.0,NaN
39,Immigrants,Foreigners,Latin America and the Caribbean,Central America,734,921,1612,3648,4087,4862,...,3346,3990,4140,5039,4891,4814,5692,5821,6019.0,NaN
40,Immigrants,Foreigners,Latin America and the Caribbean,South America,5302,5984,6831,4781,4038,4261,...,12205,13941,13884,13146,12794,13206,12577,10077,9256.0,NaN
41,Immigrants,Foreigners,Latin America and the Caribbean Total,NaN,13081,15215,16769,15427,13678,15171,...,22181,24747,24676,26011,26547,26867,28818,27856,27173.0,NaN
42,Immigrants,Foreigners,Northern America,Northern America,9378,10030,9074,7100,6661,6543,...,6990,8394,9613,9463,10190,8995,8142,7676,7891.0,NaN
43,Immigrants,Foreigners,Oceania,Australia and New Zealand,1304,1119,848,457,481,467,...,1280,1279,1193,1383,1498,1538,1423,1226,1399.0,NaN
44,Immigrants,Foreigners,Oceania,Melanesia,632,707,816,558,391,448,...,497,300,278,304,331,313,401,316,273.0,NaN
45,Immigrants,Foreigners,Oceania,Micronesia,1,..,..,1,..,..,...,1,2,1,3,1,2,..,..,2.0,NaN
46,Immigrants,Foreigners,Oceania,Polynesia,5,13,11,2,6,5,...,10,4,1,3,4,7,10,6,5.0,NaN
47,Immigrants,Foreigners,Oceania Total,NaN,1942,1839,1675,1018,878,920,...,1788,1585,1473,1693,1834,1860,1834,1548,1679.0,NaN
48,Immigrants,Foreigners,Unknown,Unknown,44000,18078,16904,13635,14855,14368,...,3739,4785,4583,4348,4197,3402,3731,2554,1681.0,NaN

In [10]:
# Replace missing data : .. to NaN
regionsByCitizenshipDf.replace("..", np.nan, inplace=True)
regionsByCitizenshipDf

,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
20,Immigrants,Citizens,Northern America,Northern America,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
21,Immigrants,Foreigners,Africa,Eastern Africa,1471.0,1641.0,1426.0,1094.0,1187.0,1134.0,...,7726.0,7083.0,6750.0,6669.0,6705.0,6922.0,8591.0,8956.0,8846.0,NaN
22,Immigrants,Foreigners,Africa,Middle Africa,33.0,27.0,44.0,32.0,42.0,30.0,...,2452.0,2802.0,2834.0,2951.0,3034.0,3255.0,3369.0,3146.0,4602.0,NaN
23,Immigrants,Foreigners,Africa,Northern Africa,1100.0,1268.0,1348.0,936.0,842.0,840.0,...,12478.0,11323.0,12705.0,11750.0,13456.0,16320.0,19271.0,15712.0,15453.0,NaN
24,Immigrants,Foreigners,Africa,Southern Africa,1041.0,1126.0,791.0,387.0,297.0,327.0,...,1203.0,1012.0,1148.0,1230.0,1184.0,1235.0,1306.0,1049.0,1348.0,NaN
25,Immigrants,Foreigners,Africa,Western Africa,306.0,301.0,210.0,222.0,271.0,319.0,...,4333.0,5303.0,5751.0,5684.0,5511.0,6802.0,8355.0,6578.0,7834.0,NaN
26,Immigrants,Foreigners,Africa Total,NaN,3951.0,4363.0,3819.0,2671.0,2639.0,2650.0,...,28192.0,27523.0,29188.0,28284.0,29890.0,34534.0,40892.0,35441.0,38083.0,NaN
27,Immigrants,Foreigners,Asia,Central Asia,NaN,NaN,NaN,NaN,NaN,NaN,...,995.0,1134.0,903.0,936.0,805.0,962.0,905.0,769.0,1029.0,NaN
28,Immigrants,Foreigners,Asia,Eastern Asia,6836.0,8895.0,5481.0,3254.0,2624.0,2979.0,...,43550.0,50306.0,41763.0,35591.0,39602.0,37497.0,37954.0,35159.0,40449.0,NaN
29,Immigrants,Foreigners,Asia,South-Eastern Asia,8693.0,9191.0,9022.0,8845.0,12161.0,9787.0,...,18056.0,22809.0,25105.0,27256.0,30614.0,34166.0,44199.0,40494.0,37695.0,NaN
30,Immigrants,Foreigners,Asia,Southern Asia,11315.0,11566.0,11591.0,10157.0,9607.0,7654.0,...,58521.0,69510.0,66742.0,56032.0,54154.0,53083.0,62284.0,53673.0,60568.0,NaN
31,Immigrants,Foreigners,Asia,Western Asia,4181.0,4662.0,4120.0,2440.0,2882.0,3430.0,...,13728.0,15494.0,14541.0,13644.0,14719.0,15726.0,18503.0,16799.0,12477.0,NaN
32,Immigrants,Foreigners,Asia Total,NaN,31025.0,34314.0,30214.0,24696.0,27274.0,23850.0,...,134850.0,159253.0,149054.0,133459.0,139894.0,141434.0,163845.0,146894.0,152218.0,NaN
33,Immigrants,Foreigners,Europe,Eastern Europe,1467.0,3698.0,6873.0,5459.0,4433.0,3969.0,...,18360.0,16724.0,14389.0,13886.0,11988.0,11759.0,11803.0,9612.0,9464.0,NaN
34,Immigrants,Foreigners,Europe,Northern Europe,23721.0,26608.0,22134.0,10725.0,10845.0,10212.0,...,8486.0,8153.0,7969.0,9186.0,10042.0,9846.0,9816.0,7285.0,7616.0,NaN
35,Immigrants,Foreigners,Europe,Southern Europe,7762.0,7037.0,5222.0,3083.0,3033.0,2868.0,...,3200.0,2806.0,2417.0,2290.0,2692.0,2948.0,2661.0,2466.0,2854.0,NaN
36,Immigrants,Foreigners,Europe,Western Europe,6810.0,7459.0,8491.0,5371.0,3976.0,3795.0,...,8036.0,8272.0,8278.0,8133.0,9970.0,10525.0,9145.0,7415.0,9243.0,NaN
37,Immigrants,Foreigners,Europe Total,NaN,39760.0,44802.0,42720.0,24638.0,22287.0,20844.0,...,38082.0,35955.0,33053.0,33495.0,34692.0,35078.0,33425.0,26778.0,29177.0,NaN
38,Immigrants,Foreigners,Latin America and the Caribbean,Caribbean,7045.0,8310.0,8326.0,6998.0,5553.0,6048.0,...,6630.0,6816.0,6652.0,7826.0,8862.0,8847.0,10549.0,11958.0,11898.0,NaN
39,Immigrants,Foreigners,Latin America and the Caribbean,Central America,734.0,921.0,1612.0,3648.0,4087.0,4862.0,...,3346.0,3990.0,4140.0,5039.0,4891.0,4814.0,5692.0,5821.0,6019.0,NaN
40,Immigrants,Foreigners,Latin America and the Caribbean,South America,5302.0,5984.0,6831.0,4781.0,4038.0,4261.0,...,12205.0,13941.0,13884.0,13146.0,12794.0,13206.0,12577.0,10077.0,9256.0,NaN
41,Immigrants,Foreigners,Latin America and the Caribbean Total,NaN,13081.0,15215.0,16769.0,15427.0,13678.0,15171.0,...,22181.0,24747.0,24676.0,26011.0,26547.0,26867.0,28818.0,27856.0,27173.0,NaN
42,Immigrants,Foreigners,Northern America,Northern America,9378.0,10030.0,9074.0,7100.0,6661.0,6543.0,...,6990.0,8394.0,9613.0,9463.0,10190.0,8995.0,8142.0,7676.0,7891.0,NaN
43,Immigrants,Foreigners,Oceania,Australia and New Zealand,1304.0,1119.0,848.0,457.0,481.0,467.0,...,1280.0,1279.0,1193.0,1383.0,1498.0,1538.0,1423.0,1226.0,1399.0,NaN
44,Immigrants,Foreigners,Oceania,Melanesia,632.0,707.0,816.0,558.0,391.0,448.0,...,497.0,300.0,278.0,304.0,331.0,313.0,401.0,316.0,273.0,NaN
45,Immigrants,Foreigners,Oceania,Micronesia,1.0,NaN,NaN,1.0,NaN,NaN,...,1.0,2.0,1.0,3.0,1.0,2.0,NaN,NaN,2.0,NaN
46,Immigrants,Foreigners,Oceania,Polynesia,5.0,13.0,11.0,2.0,6.0,5.0,...,10.0,4.0,1.0,3.0,4.0,7.0,10.0,6.0,5.0,NaN
47,Immigrants,Foreigners,Oceania Total,NaN,1942.0,1839.0,1675.0,1018.0,878.0,920.0,...,1788.0,1585.0,1473.0,1693.0,1834.0,1860.0,1834.0,1548.0,1679.0,NaN
48,Immigrants,Foreigners,Unknown,Unknown,44000.0,18078.0,16904.0,13635.0,14855.0,14368.0,...,3739.0,4785.0,4583.0,4348.0,4197.0,3402.0,3731.0,2554.0,1681.0,NaN

In [11]:
# Code to find missing data location on Dataframe, NaN
missing_data = regionsByCitizenshipDf.isnull()
columnsWithNan = 0

for column in missing_data.columns.values.tolist():
    if regionsByCitizenshipDf[column].isnull().values.any():
        columnsWithNan = columnsWithNan + 1
        print(column)
        print(missing_data[column].value_counts())
        print("")
        
print("Columns with NaN: ", columnsWithNan)

RegName
False    24
True      5
Name: RegName, dtype: int64

1980
False    27
True      2
Name: 1980, dtype: int64

1981
False    26
True      3
Name: 1981, dtype: int64

1982
False    26
True      3
Name: 1982, dtype: int64

1983
False    27
True      2
Name: 1983, dtype: int64

1984
False    26
True      3
Name: 1984, dtype: int64

1985
False    26
True      3
Name: 1985, dtype: int64

1986
False    26
True      3
Name: 1986, dtype: int64

1987
False    26
True      3
Name: 1987, dtype: int64

1988
False    27
True      2
Name: 1988, dtype: int64

1989
False    27
True      2
Name: 1989, dtype: int64

1990
False    27
True      2
Name: 1990, dtype: int64

1991
False    27
True      2
Name: 1991, dtype: int64

1992
False    28
True      1
Name: 1992, dtype: int64

1994
False    28
True      1
Name: 1994, dtype: int64

1997
False    27
True      2
Name: 1997, dtype: int64

1998
False    28
True      1
Name: 1998, dtype: int64

1999
False    28
True      1
Name: 1999, dtype: int64

2000
False    28
True      1
Name: 2000, dtype: int64

2001
False    28
True      1
Name: 2001, dtype: int64

2002
False    28
True      1
Name: 2002, dtype: int64

2003
False    28
True      1
Name: 2003, dtype: int64

2004
False    28
True      1
Name: 2004, dtype: int64

2005
False    28
True      1
Name: 2005, dtype: int64

2006
False    28
True      1
Name: 2006, dtype: int64

2007
False    28
True      1
Name: 2007, dtype: int64

2008
False    28
True      1
Name: 2008, dtype: int64

2009
False    28
True      1
Name: 2009, dtype: int64

2010
False    27
True      2
Name: 2010, dtype: int64

2011
False    28
True      1
Name: 2011, dtype: int64

2013
True    29
Name: 2013, dtype: int64

Columns with NaN:  31

In [12]:
# Loop equal to next scope to don't waste time
missing_data = regionsByCitizenshipDf.isnull()

for column in missing_data.columns.values.tolist():
    if regionsByCitizenshipDf[column].isnull().values.any():
        regionsByCitizenshipDf[column].replace(np.nan, "0", inplace=True)

In [13]:
# Replace NaN value in whole Dataframe by 0
regionsByCitizenshipDf["RegName"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1980"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1981"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1982"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1983"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1984"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1985"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1986"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1987"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1988"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1989"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1990"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1991"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1992"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1994"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1997"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1998"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["1999"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2000"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2001"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2002"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2003"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2004"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2005"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2006"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2007"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2008"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2009"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2010"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2011"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf["2013"].replace(np.nan, "0", inplace=True)
regionsByCitizenshipDf

,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
20,Immigrants,Citizens,Northern America,Northern America,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1.0,1.0,0
21,Immigrants,Foreigners,Africa,Eastern Africa,1471.0,1641.0,1426.0,1094.0,1187.0,1134.0,...,7726.0,7083.0,6750.0,6669.0,6705.0,6922.0,8591.0,8956.0,8846.0,0
22,Immigrants,Foreigners,Africa,Middle Africa,33.0,27.0,44.0,32.0,42.0,30.0,...,2452.0,2802.0,2834.0,2951.0,3034.0,3255.0,3369.0,3146.0,4602.0,0
23,Immigrants,Foreigners,Africa,Northern Africa,1100.0,1268.0,1348.0,936.0,842.0,840.0,...,12478.0,11323.0,12705.0,11750.0,13456.0,16320.0,19271.0,15712.0,15453.0,0
24,Immigrants,Foreigners,Africa,Southern Africa,1041.0,1126.0,791.0,387.0,297.0,327.0,...,1203.0,1012.0,1148.0,1230.0,1184.0,1235.0,1306.0,1049.0,1348.0,0
25,Immigrants,Foreigners,Africa,Western Africa,306.0,301.0,210.0,222.0,271.0,319.0,...,4333.0,5303.0,5751.0,5684.0,5511.0,6802.0,8355.0,6578.0,7834.0,0
26,Immigrants,Foreigners,Africa Total,0,3951.0,4363.0,3819.0,2671.0,2639.0,2650.0,...,28192.0,27523.0,29188.0,28284.0,29890.0,34534.0,40892.0,35441.0,38083.0,0
27,Immigrants,Foreigners,Asia,Central Asia,0,0,0,0,0,0,...,995.0,1134.0,903.0,936.0,805.0,962.0,905.0,769.0,1029.0,0
28,Immigrants,Foreigners,Asia,Eastern Asia,6836.0,8895.0,5481.0,3254.0,2624.0,2979.0,...,43550.0,50306.0,41763.0,35591.0,39602.0,37497.0,37954.0,35159.0,40449.0,0
29,Immigrants,Foreigners,Asia,South-Eastern Asia,8693.0,9191.0,9022.0,8845.0,12161.0,9787.0,...,18056.0,22809.0,25105.0,27256.0,30614.0,34166.0,44199.0,40494.0,37695.0,0
30,Immigrants,Foreigners,Asia,Southern Asia,11315.0,11566.0,11591.0,10157.0,9607.0,7654.0,...,58521.0,69510.0,66742.0,56032.0,54154.0,53083.0,62284.0,53673.0,60568.0,0
31,Immigrants,Foreigners,Asia,Western Asia,4181.0,4662.0,4120.0,2440.0,2882.0,3430.0,...,13728.0,15494.0,14541.0,13644.0,14719.0,15726.0,18503.0,16799.0,12477.0,0
32,Immigrants,Foreigners,Asia Total,0,31025.0,34314.0,30214.0,24696.0,27274.0,23850.0,...,134850.0,159253.0,149054.0,133459.0,139894.0,141434.0,163845.0,146894.0,152218.0,0
33,Immigrants,Foreigners,Europe,Eastern Europe,1467.0,3698.0,6873.0,5459.0,4433.0,3969.0,...,18360.0,16724.0,14389.0,13886.0,11988.0,11759.0,11803.0,9612.0,9464.0,0
34,Immigrants,Foreigners,Europe,Northern Europe,23721.0,26608.0,22134.0,10725.0,10845.0,10212.0,...,8486.0,8153.0,7969.0,9186.0,10042.0,9846.0,9816.0,7285.0,7616.0,0
35,Immigrants,Foreigners,Europe,Southern Europe,7762.0,7037.0,5222.0,3083.0,3033.0,2868.0,...,3200.0,2806.0,2417.0,2290.0,2692.0,2948.0,2661.0,2466.0,2854.0,0
36,Immigrants,Foreigners,Europe,Western Europe,6810.0,7459.0,8491.0,5371.0,3976.0,3795.0,...,8036.0,8272.0,8278.0,8133.0,9970.0,10525.0,9145.0,7415.0,9243.0,0
37,Immigrants,Foreigners,Europe Total,0,39760.0,44802.0,42720.0,24638.0,22287.0,20844.0,...,38082.0,35955.0,33053.0,33495.0,34692.0,35078.0,33425.0,26778.0,29177.0,0
38,Immigrants,Foreigners,Latin America and the Caribbean,Caribbean,7045.0,8310.0,8326.0,6998.0,5553.0,6048.0,...,6630.0,6816.0,6652.0,7826.0,8862.0,8847.0,10549.0,11958.0,11898.0,0
39,Immigrants,Foreigners,Latin America and the Caribbean,Central America,734.0,921.0,1612.0,3648.0,4087.0,4862.0,...,3346.0,3990.0,4140.0,5039.0,4891.0,4814.0,5692.0,5821.0,6019.0,0
40,Immigrants,Foreigners,Latin America and the Caribbean,South America,5302.0,5984.0,6831.0,4781.0,4038.0,4261.0,...,12205.0,13941.0,13884.0,13146.0,12794.0,13206.0,12577.0,10077.0,9256.0,0
41,Immigrants,Foreigners,Latin America and the Caribbean Total,0,13081.0,15215.0,16769.0,15427.0,13678.0,15171.0,...,22181.0,24747.0,24676.0,26011.0,26547.0,26867.0,28818.0,27856.0,27173.0,0
42,Immigrants,Foreigners,Northern America,Northern America,9378.0,10030.0,9074.0,7100.0,6661.0,6543.0,...,6990.0,8394.0,9613.0,9463.0,10190.0,8995.0,8142.0,7676.0,7891.0,0
43,Immigrants,Foreigners,Oceania,Australia and New Zealand,1304.0,1119.0,848.0,457.0,481.0,467.0,...,1280.0,1279.0,1193.0,1383.0,1498.0,1538.0,1423.0,1226.0,1399.0,0
44,Immigrants,Foreigners,Oceania,Melanesia,632.0,707.0,816.0,558.0,391.0,448.0,...,497.0,300.0,278.0,304.0,331.0,313.0,401.0,316.0,273.0,0
45,Immigrants,Foreigners,Oceania,Micronesia,1.0,0,0,1.0,0,0,...,1.0,2.0,1.0,3.0,1.0,2.0,0,0,2.0,0
46,Immigrants,Foreigners,Oceania,Polynesia,5.0,13.0,11.0,2.0,6.0,5.0,...,10.0,4.0,1.0,3.0,4.0,7.0,10.0,6.0,5.0,0
47,Immigrants,Foreigners,Oceania Total,0,1942.0,1839.0,1675.0,1018.0,878.0,920.0,...,1788.0,1585.0,1473.0,1693.0,1834.0,1860.0,1834.0,1548.0,1679.0,0
48,Immigrants,Foreigners,Unknown,Unknown,44000.0,18078.0,16904.0,13635.0,14855.0,14368.0,...,3739.0,4785.0,4583.0,4348.0,4197.0,3402.0,3731.0,2554.0,1681.0,0

In [14]:
# Replace RegName column fields with value 0 to ""
regionsByCitizenshipDf["RegName"].replace("0", "", inplace=True)
regionsByCitizenshipDf

,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
20,Immigrants,Citizens,Northern America,Northern America,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1.0,1.0,0
21,Immigrants,Foreigners,Africa,Eastern Africa,1471.0,1641.0,1426.0,1094.0,1187.0,1134.0,...,7726.0,7083.0,6750.0,6669.0,6705.0,6922.0,8591.0,8956.0,8846.0,0
22,Immigrants,Foreigners,Africa,Middle Africa,33.0,27.0,44.0,32.0,42.0,30.0,...,2452.0,2802.0,2834.0,2951.0,3034.0,3255.0,3369.0,3146.0,4602.0,0
23,Immigrants,Foreigners,Africa,Northern Africa,1100.0,1268.0,1348.0,936.0,842.0,840.0,...,12478.0,11323.0,12705.0,11750.0,13456.0,16320.0,19271.0,15712.0,15453.0,0
24,Immigrants,Foreigners,Africa,Southern Africa,1041.0,1126.0,791.0,387.0,297.0,327.0,...,1203.0,1012.0,1148.0,1230.0,1184.0,1235.0,1306.0,1049.0,1348.0,0
25,Immigrants,Foreigners,Africa,Western Africa,306.0,301.0,210.0,222.0,271.0,319.0,...,4333.0,5303.0,5751.0,5684.0,5511.0,6802.0,8355.0,6578.0,7834.0,0
26,Immigrants,Foreigners,Africa Total,,3951.0,4363.0,3819.0,2671.0,2639.0,2650.0,...,28192.0,27523.0,29188.0,28284.0,29890.0,34534.0,40892.0,35441.0,38083.0,0
27,Immigrants,Foreigners,Asia,Central Asia,0,0,0,0,0,0,...,995.0,1134.0,903.0,936.0,805.0,962.0,905.0,769.0,1029.0,0
28,Immigrants,Foreigners,Asia,Eastern Asia,6836.0,8895.0,5481.0,3254.0,2624.0,2979.0,...,43550.0,50306.0,41763.0,35591.0,39602.0,37497.0,37954.0,35159.0,40449.0,0
29,Immigrants,Foreigners,Asia,South-Eastern Asia,8693.0,9191.0,9022.0,8845.0,12161.0,9787.0,...,18056.0,22809.0,25105.0,27256.0,30614.0,34166.0,44199.0,40494.0,37695.0,0
30,Immigrants,Foreigners,Asia,Southern Asia,11315.0,11566.0,11591.0,10157.0,9607.0,7654.0,...,58521.0,69510.0,66742.0,56032.0,54154.0,53083.0,62284.0,53673.0,60568.0,0
31,Immigrants,Foreigners,Asia,Western Asia,4181.0,4662.0,4120.0,2440.0,2882.0,3430.0,...,13728.0,15494.0,14541.0,13644.0,14719.0,15726.0,18503.0,16799.0,12477.0,0
32,Immigrants,Foreigners,Asia Total,,31025.0,34314.0,30214.0,24696.0,27274.0,23850.0,...,134850.0,159253.0,149054.0,133459.0,139894.0,141434.0,163845.0,146894.0,152218.0,0
33,Immigrants,Foreigners,Europe,Eastern Europe,1467.0,3698.0,6873.0,5459.0,4433.0,3969.0,...,18360.0,16724.0,14389.0,13886.0,11988.0,11759.0,11803.0,9612.0,9464.0,0
34,Immigrants,Foreigners,Europe,Northern Europe,23721.0,26608.0,22134.0,10725.0,10845.0,10212.0,...,8486.0,8153.0,7969.0,9186.0,10042.0,9846.0,9816.0,7285.0,7616.0,0
35,Immigrants,Foreigners,Europe,Southern Europe,7762.0,7037.0,5222.0,3083.0,3033.0,2868.0,...,3200.0,2806.0,2417.0,2290.0,2692.0,2948.0,2661.0,2466.0,2854.0,0
36,Immigrants,Foreigners,Europe,Western Europe,6810.0,7459.0,8491.0,5371.0,3976.0,3795.0,...,8036.0,8272.0,8278.0,8133.0,9970.0,10525.0,9145.0,7415.0,9243.0,0
37,Immigrants,Foreigners,Europe Total,,39760.0,44802.0,42720.0,24638.0,22287.0,20844.0,...,38082.0,35955.0,33053.0,33495.0,34692.0,35078.0,33425.0,26778.0,29177.0,0
38,Immigrants,Foreigners,Latin America and the Caribbean,Caribbean,7045.0,8310.0,8326.0,6998.0,5553.0,6048.0,...,6630.0,6816.0,6652.0,7826.0,8862.0,8847.0,10549.0,11958.0,11898.0,0
39,Immigrants,Foreigners,Latin America and the Caribbean,Central America,734.0,921.0,1612.0,3648.0,4087.0,4862.0,...,3346.0,3990.0,4140.0,5039.0,4891.0,4814.0,5692.0,5821.0,6019.0,0
40,Immigrants,Foreigners,Latin America and the Caribbean,South America,5302.0,5984.0,6831.0,4781.0,4038.0,4261.0,...,12205.0,13941.0,13884.0,13146.0,12794.0,13206.0,12577.0,10077.0,9256.0,0
41,Immigrants,Foreigners,Latin America and the Caribbean Total,,13081.0,15215.0,16769.0,15427.0,13678.0,15171.0,...,22181.0,24747.0,24676.0,26011.0,26547.0,26867.0,28818.0,27856.0,27173.0,0
42,Immigrants,Foreigners,Northern America,Northern America,9378.0,10030.0,9074.0,7100.0,6661.0,6543.0,...,6990.0,8394.0,9613.0,9463.0,10190.0,8995.0,8142.0,7676.0,7891.0,0
43,Immigrants,Foreigners,Oceania,Australia and New Zealand,1304.0,1119.0,848.0,457.0,481.0,467.0,...,1280.0,1279.0,1193.0,1383.0,1498.0,1538.0,1423.0,1226.0,1399.0,0
44,Immigrants,Foreigners,Oceania,Melanesia,632.0,707.0,816.0,558.0,391.0,448.0,...,497.0,300.0,278.0,304.0,331.0,313.0,401.0,316.0,273.0,0
45,Immigrants,Foreigners,Oceania,Micronesia,1.0,0,0,1.0,0,0,...,1.0,2.0,1.0,3.0,1.0,2.0,0,0,2.0,0
46,Immigrants,Foreigners,Oceania,Polynesia,5.0,13.0,11.0,2.0,6.0,5.0,...,10.0,4.0,1.0,3.0,4.0,7.0,10.0,6.0,5.0,0
47,Immigrants,Foreigners,Oceania Total,,1942.0,1839.0,1675.0,1018.0,878.0,920.0,...,1788.0,1585.0,1473.0,1693.0,1834.0,1860.0,1834.0,1548.0,1679.0,0
48,Immigrants,Foreigners,Unknown,Unknown,44000.0,18078.0,16904.0,13635.0,14855.0,14368.0,...,3739.0,4785.0,4583.0,4348.0,4197.0,3402.0,3731.0,2554.0,1681.0,0

In [15]:
regionsByCitizenshipDf.to_excel("P2_T1.xlsx")